### ISSUE TITLE
Ugly app icon

### ISSUE THREAD

**Issue by intialonso** [andrew-bibb/cmst#107]
I think that the icon of this wonderful app needs a rework. Maybe something more simple (without text), even generic will be better (use the system network one).

**Comment by andrew-bibb** [comment]
The icon came from the issue linked below:

https://github.com/andrew-bibb/cmst/issues/51

As I mention in that thread, I have the artistic ability of your average rock.  Additionally the closest I come to an application launcher on my system is dmenu so I actually never have to look at the icon.  That issue was flagged "help wanted", so if you want to submit some artwork  I'll be happy to look at and will probably build it in as the guy who submitted the art no longer uses this program (he went to wicd). If you do submit something I need either a license or a clear statement that the icons are your original work and provided to this project, the public domain, so whatever you feel is appropriate.

**Comment by intialonso** [comment]
I was thinking that the best solution is to use the system theme icons, this way you have consistency secured no matter what.

According to the Freedesktop specs the "preferences-system-network" will be the one to use.

**Comment by agaida** [comment]
+1

**Comment by progandy** [comment]
I have a rough idea for an icon, but I am no graphics designer, so it looks a bit unclean and doesn't scale well to smaller sizes.
![cmst](https://cloud.githubusercontent.com/assets/1003865/9565514/b59f4854-4ed3-11e5-9f19-d203393e50b1.png)

**Comment by agaida** [comment]
please go with the suggestion @intialonso made - application icons for standard tasks should be used for standard tasks

**Comment by andrew-bibb** [comment]
Progandy - you are a much better graphics designer than I am - looks great.  I put one of my kids through school to get a BFA in computer animation.  After all that I think he owes me so I might kick this over to him to see what he can do at the smaller sizes.

agaida and intialonso - understand about using the standard icons.  Been enjoying one of the few real summer weekends we've had this year so I've not looked at this at all since Friday.  My initial sense is I won't be able to do it because the icon name needs to be known (that means full name and path) at build time since the Window Manager handles all display instances, including putting it into the window title bar.  For the icons used inside the application we only need to make the decision at run time so I can, and do, handle those in the code.  Anyway, that is my first cut.  Still need to formally research the answer and if it is possible I'll try and implement it, at least as an option at build time.

**Comment by intialonso** [comment]
But this just require to change the Icon line in the .desktop file in /usr/share/applications this is the stardard of the Freedesktop specs.

```
[Desktop Entry]
Type=Application
Version=1.1
Name=Network Configuration
GenericName=Network Configuration
Comment=QT GUI frontend for connman
Categories=Settings;System;Qt;NetworkSettings
Icon=preferences-system-network
Terminal=false
Exec=cmst
Terminal=false
StartupNotify=false
X-GNOME-Autostart-enabled=true

Name[de]=Netzwerk-Konfiguration

```
And you got this:

Using Numix Circle:
![captura de pantalla de 2015-09-05 10 46 27](https://cloud.githubusercontent.com/assets/7544231/9700042/9ef432e4-53bb-11e5-8dc7-5c60b3ddcd53.png)

Using Elementary:
![captura de pantalla de 2015-09-05 10 48 52](https://cloud.githubusercontent.com/assets/7544231/9700053/e3179cea-53bb-11e5-8383-e2fc41d61553.png)

**Comment by agaida** [comment]
second that - one should not reinvent the wheel everytime - following standard may not sound innovative, but it make it easier for users of our programs and applications.

**Comment by andrew-bibb** [comment]
The standards I've been following are contained in this document:
http://doc.qt.io/qt-5/appicon.html

I have spent a bit of time looking at what I can do to include system icons you want instead of the built in ones (which will change to a variation of Progandy's suggestion).  It is looking like this will just entail adding one or two test statements to the build files.

It is on the list, hopefully I'll be able to bust it off in the next couple of days.  Haven't used a test in a QT project file before so might take me a day or two working out the details.

**Comment by andrew-bibb** [comment]
I just uploaded code which should allow the use of the freedesktop **preferences-system-network** icon in lieu of the CMST icon.  I need to update the wiki with directions, but if you want to try it out go into the /images/application directory and remove the cmst.icon file, and then a normal build (qmake, make, make install).  Without that icon there both the desktop files and the internal program icons should default to the theme icon. 

I'm going to leave this one open until I get the artwork from Progandy back as something about 24x24.

**Comment by andrew-bibb** [comment]
The icon from Progandy is now the official CMST icon, and thank you, I think it looks great.  Converted it to SVG for use inside the program and that seems to solve a lot of the scaling issues.  For the fixed size I used imagemagick, worked like a charm.

Description of how to not use it but use icon preferences-system-network is described on this page in the [wiki](https://github.com/andrew-bibb/cmst/wiki/Application-Icon)

**Comment by hagabaka** [comment]
The png version of app icon doesn't look very clear, and the svg seems to just embed a bitmap.
![cmst](https://cloud.githubusercontent.com/assets/11416/10271817/9d479b4e-6ae4-11e5-80b5-6d466fcc32e4.png)

Unfortunately I think Progandy's icon concept is too complex to look good scaled down. I made a simpler icon with some inspiration from it:

![cmst-icon-screenshots](https://hagabaka.github.io/files/cmst-icon/cmst-icon-screenshots.png)

Here are links to the:
[svg](https://hagabaka.github.io/files/cmst-icon/cmst-icon.svg)
[16px png](https://hagabaka.github.io/files/cmst-icon/cmst-icon-16px.png)
[24px png](https://hagabaka.github.io/files/cmst-icon/cmst-icon-24px.png)

Of course anyone feel free to make improvements, and if it's good I'd be happy to make a pull request.

**Comment by andrew-bibb** [comment]
The svg version is only used internally (window icon if you have one and in the About dialog box). The other fixed sizes are for the desktop files and anything outside the program that needs them. These look great as well, and you are right they look better created from scratch that size.  I've reopened this and I'll probably build them in.  Should not need a PR, I can get them from the links above.

Thank you.

**Comment by hagabaka** [comment]
At least LxQt and OpenBox seem to be able to use the svg icon, and I'm sure the bigger DEs and window managers can too.

**Comment by andrew-bibb** [comment]
LxQt does not surprise me, but OpenBox kind of does.  I'm running barebones i3 and SVG icons are not picked up in desktop files.  Anyway the install and project files are set up to use both and you've got both so we should be set.

**Comment by andrew-bibb** [comment]
I've built in the new icons as default and posted updated code to GitHub.  I did manage to get my i3 to pickup the SVG ones if that was the only one provided.  Not sure what the problem was, but I uninstalled the hicolor package then reinstalled it and I was able to pick it up.  

I also changed the default not scalable icon from 24x24 to 48x48.  Seems to be what Freedesktop.org recommends.  

I'm going to close this one out again.  Thanks to all who participated and provided artwork.
