### ISSUE TITLE
Needed dependencies

### ISSUE THREAD

**Issue by agaida** [andrew-bibb/cmst#115]
One should mention that since Commit 1df3ec608715da6bd20715890aaad263f8fe851e cmst depend on Qt >= 5.4 because of:
<pre>code/main.cpp: In function 'int main(int, char**)':
code/main.cpp:171:40: error: 'class QCommandLineParser' has no member named 'showVersion'
   if (parser.isSet("version") ) parser.showVersion();
</pre>
showVersion is introduced in Qt 5.4 - that means, the current version of cmst will not run with debian stable and all ubuntu versions before 15.04 (Vivid Vervet) - or better, all distributions that use Qt 5.3.x

**Comment by andrew-bibb** [comment]
Thank you.  I remember putting it in a couple of weeks back, specifically because I thought it was there and was surprised it wasn't.

What I'll probably do is the same thing I did with the qUtf8Printable macro.  Put in a test in the code for QT version and use the 5.4 functions if available.   These tests are already scattered all around the code so one or two more won't hurt anything.  It is checked at the preprocessor stage so it does not add anything to the compiled code.   None of these are at all important to using the program, and it is silly to limit people using this if their distro has not gone up to 5.4 yet.  

I'll move this one to the top of the list.

**Comment by andrew-bibb** [comment]
I just uploaded code to github which should check the QT version number before trying to call parser.showVersion(). If someone is running 5.3 or earlier they should still get a version from the command line using -v, just one we create ourselves.   

If this fixes it let me know and I'll close the issue, or you can close it if you would prefer.

**Comment by agaida** [comment]
will check this tomorrow, its now 02:06 in the morning - head->bed :)

**Comment by andrew-bibb** [comment]
By all means - bed.  

No rush on this end - wifey has been away for 10 days and I'm madly cleaning and picking up before she returns tomorrow.

**Comment by agaida** [comment]
unfortunally the situation has changed only a little bit - the Qt 5.4 part is ok, but the Part for Qt < 5.4 not
<pre>
  code/main.cpp:175:135: error: 'qInfo' was not declared in this scope
     qInfo("%s %s", qPrintable(LONG_NAME), qPrintable(VERSION) );
</pre>

**Comment by andrew-bibb** [comment]
Odd, I forced the < 5.4 code to compile and ran it here just fine.

I've uploaded a small fix to include QtGlobal at the top of main.cpp. Usually supplying the include solves "not declared in this scope" errors.  If this does not work I'll just remove the -v option for anyone not running 5.4, or maybe I'll just remove it period.
