### ISSUE TITLE
CMST too large when screen < 600px

### ISSUE THREAD

**Issue by flamusdiu** [andrew-bibb/cmst#122]
I have a friend who has a Netbook with a horizontal screen size of around 600px which causes CMST to be way outside the viewing window and nearly impossible to close (if you don't know the key stroke). 

If you need, I can try and get some screenshots from him. Though, I've been asking about them. =P

**Comment by andrew-bibb** [comment]
I'll see what I can do. As I recall finding the display resolution inside QT can be tough, so I may need to implement a feature to open at a specific size.  My memory is a bit foggy on the display resolution thing, haven't had the need to do it in a while so I'll have to dig into the QT documentation. 

Right now the only option for size is to start the program minimized in the tray or normal mode on the screen. Maybe not a bad idea to provide a size option for something in between, but either way I should be able to do something about it.

**Comment by flamusdiu** [comment]
Starting minimized isn't a bad idea by default. Most people are probably
more comfortable with it going to the tray at start-up then having to
change the autostart configuration to add the "-m".

**Comment by andrew-bibb** [comment]
Was way easier than I thought.  Think the problem I was having before was relating image pixels to screen pixels, but does not really matter I guess.

What it does now is check the size of the default screen and scales the UI down to fit (plus a little buffer).  Since I don't have a small screen I've tested by forcing it to the screen size on my system.  Seems to scale properly, but if there are any problems just reopen the issue.

I had thought about changing the default behavior but that would mess things up for a lot of people.  It is really not necessary to change the autostart file, in the Preferences tab just make sure "Use Start Options" and "Start Minimized" are both checked.  That will do it for you.

**Comment by flamusdiu** [comment]
I'll have to check with him. Thanks!
