### ISSUE TITLE
icon size 1200x1200

### ISSUE THREAD

**Issue by agaida** [andrew-bibb/cmst#127]
W: cmst: icon-size-and-directory-name-mismatch usr/share/icons/hicolor/48x48/apps/cmst.png 1200x1200

hmm. 48x48 should be enough. really :)

**Comment by andrew-bibb** [comment]
It used to be svg which is a lot easier for me.  I removed the svg versions because it required an extra dependency (at least on Arch Linux).  Let me see if I can shrink it and still have it look good.

**Comment by progandy** [comment]
I think you should provide the icon in different sizes. Put the svg icon in /scalable, and then choose some common png sizes (e.g. 16x16, 32x32, 48x48) and then one that fits the size you use in your dialogs. Usually icons are used in one of these sizes:
```scalable```, ```16x16```, ```20x20```, ```22x22```, ```24x24```, ```32x32```, ```36x36```, ```40x40```, ```48x48```, ```64x64```, ```72x72```, ```96x96```, ```128x128```, ```192x192```, ```256x256```, ```384x384```, ```512x512```

**Comment by andrew-bibb** [comment]
SVG icons in /scalable are the easiest. All I really need is the one in svg format and it is scaled up or down automatically.  To use them internally however the package qt5-svg has to be installed.  It is not a very large package, but I was trying to remove as many dependencies as I could.  It was a while back, but as I recall .desktop files would find and use the svg icon, but CMST would not without the svg package.  The icon only appears in some of the "About" dialogs (and maybe the window bar, but I'm not positive on that since I use I3 and there is no icon in the bar) so really not a huge deal I guess.

QT really only needs one size, it handles scaling pretty well, but best to pick one more or less the final size.  I picked the 48x48 from this site which gives a recommendation for minimum desktop icon size:
https://developer.gnome.org/integration-guide/stable/icons.html.en
That way I could use it in the program and the .desktop files could also use it.  It is though 1200x1200.  I really though I had scaled it down - obviously didn't, or didn't in the program directory.

**Comment by agaida** [comment]
http://webadventures.at/2012/04/29/convert-svg-png/ - and its only a build dependency, right now i do this with inkscape, but rsvg should be sufficient. Sample Makefile snippet
<pre>
create-icons:
        for i in 16 22 32 48 64 128; do \
            mkdir -p "icons/hicolor/$${i}x$${i}/apps" ; \
            inkscape --export-width=$${i} \
                 --export-height=$${i} \
                 --export-png="$(CURDIR)/icons/hicolor/$${i}x$${i}/apps/siduction-irc.png" \
                 $(CURDIR)/icons/siduction-irc.svg ; \
        done
        convert icons/hicolor/32x32/apps/siduction-irc.png icons/siduction-irc.xpm
</pre>
should be simple with rsvg

**Comment by andrew-bibb** [comment]
Now that is cool.  I'll take a look at inkscape, up to now I've been using imagemagik.

I was thinking after my last post, there is really no harm in adding the svg icon as well.  If someone has the QT dependency it will be used, if not then the png versions would be used as fallbacks.

I'm getting too hung up on trying to reduce the dependencies, I know a lot of people don't like QT so I've really been trying to minimize it.

**Comment by agaida** [comment]
providing scalable icons is a really good idea and best practice - but providing png is also good for environments like fluxbox or so - and i know a lot of people that combine flux or $unusual_WM + qt

**Comment by progandy** [comment]
@agaida: rsvg-convert alone doesn't work, it crops this image instead of resizing it, but you can resize it after the conversion with imagemagick.

**Comment by agaida** [comment]
@progandy: Nice to know - ok, a convert like in the snippet might solve that

**Comment by andrew-bibb** [comment]
Been playing around with imagemagik and I found some settings that seem to give good reductions on the svg base.  I've used a modification of the script from agaida to create all the icon sizes suggested by progandy.

The QMake .pro file has been modified to install all of them plus the svg one.  I'm going to modify the WIki next to bring it up to date.  It is still possible to have no icon and use the system theme network configurations (I forget the issue number).
