### ISSUE TITLE
WIFI Access Points are not auto-connected 

### ISSUE THREAD

**Issue by flamusdiu** [andrew-bibb/cmst#133]
Usually when connected to an access point, it is "Favorite" status is enabled. This should allow it to auto-connect within range, however none of my access points auto-connect. Even worst, I have to readd in the wifi password even if it's already been added and shows up in the "settings" file for that access point.

**Comment by andrew-bibb** [comment]
A couple of things.  Favorite does not mean you get an autoconnect.  To get that you need to enable the "AutoConnect" property for each specific WiFi service you want to autoconnect.  Easiest place to do that is to click the "Configuration" button in the lower right corner of the "Details" tab.  I'm doing this from memory, but I believe the first page that opens displays a checkbox to enable AutoConnect for that service.  Once checked autoconnect is supposed to do that to any service marked "Favorite" that it finds.  Connman has an internal algorithm to find the best one if more than one such service located.  

The password not being saved is really odd.  That is what Favorite means. I'm not at my developement computer (nor even in the same town) at the moment, but when I get back I may ask you to post some configuration files created by Connman.

**Comment by flamusdiu** [comment]
Ahh, gotcha. It usually sets to auto-connect when it marks it as a favorite. It odd.

If I enable Wifi based on #132 , I would have to click on the "Wireless" -> SSID, then wait about 60s for the configuration popup. Add the password (even if I know it was saved). If it takes too long, I click "Disconnect" then try to connect again. However, sometimes on this second connect, it just connects fine. I don't know why it's doing that.

**Comment by andrew-bibb** [comment]
I think this may be related to #132, I'll answer some more over there, but to some of the questions above.

I should note that behavior I'm describing is completely on the Connman end.  All CMST does for managing technologies and connecting services is listen on DBus for signals from Connman, and in the case of connecting we send a DBus method call.  AutoConnect is the same, we just send a method call to set that property in the Connman service.  All the heavy lifting behind the scenes is done by Connman.

I'm not sure what was happening when AutoConnect was being set when a service was marked favorite, but that is not the way it is supposed to work according to the Connman documentation.  A connection is only marked "Favorite" once you've made a connection to it, and the only way to unmark it is to click the "Remove" button in the Wireless tab.  All remove really does is send the remove() method to the Connman service which then removes the password from the settings file in the service directory under /var/lib/connman. If you are seeing a Favorite icon in CMST then Connman is reporting that the password exists.   

Once you repower the Wifi from the first tab, so long as AutoConnect is enabled and the service is found, it should reconnect you automatically.  I just did that exact thing with my laptop and it worked fine. 

The long wait is something with dbus timing out.  I've seen it before and it usually happens when I'm testing something and corrupting files left and right.  

Two things I'd suggest.  FIrst stop CMST and Connman (systemctl stop connman), then get into /var/lib/connman and completely remove the direcory for the WiFi service giving you problems.  Restart Connman (systemctl start connman), restart CMST, and try to make the connection fresh.  You should get connected within seconds after you provide the password.

If you are still getting the problem where it does not come back after you enable, run the following from the command line:
connmanctl
scan wifi     <== wait for it to return, may take 5 or 10 seconds
services

Tell me what it says after services, I'm particularly interested in the first column after the * .

To quit connmanctl type quit.

**Comment by flamusdiu** [comment]
Will do. I'll try this weekend to play with it. Let you know.

**Comment by flamusdiu** [comment]
It's odd ... doesn't connman save it's configurations in `/var/lib/connman` by default? Or did something change?

**Comment by andrew-bibb** [comment]
Yes, configuration files created by connman are found in /var/lib/connman. I know of no way to change that.  Are they not there?

**Comment by flamusdiu** [comment]
Yup, I removed all the config files and now it doesn't create new
configurations. If I disconnect from a AP, I have to re-add the password
again. It's frustrating. I just noticed this part today. I bet if I
manually created the files, it would kinda work. =P

**Comment by andrew-bibb** [comment]
That is odd.  I'd try skipping CMST and using connmanctl.  It will be something like:
    `connmanctl`
     `scan wifi`
     `services`
     `agent on`
     `connect` THE WIFI SERVICE`

With the agent on you should be prompted to enter a password for the connection.  If connmanctl does not create the files then you've got some problem with your connman installation.

**Comment by andrew-bibb** [comment]
This has been quiet for a bit, I'm going to close it out to clean things up.  If you think it should be kept open you can reopen or let me know
