### ISSUE TITLE
rename french translation file

### ISSUE THREAD

**Issue by agaida** [andrew-bibb/cmst#142]
i suggest to rename translations/cmst_fr_FR.ts. to translations/cmst_fr_FR.ts

**Comment by andrew-bibb** [comment]
I see that.  Don't think I ever got any translations back after I created the files, so probably not a huge issue.  Still though, needs to be changed.

May not happen for a couple of days however. I threw out my back this weekend and at the moment sitting in front of a computer to work is quite uncomfortable.  I'm typing this from a laptop while laying down - hardly ideal for real work.

**Comment by agaida** [comment]
get well soon

**Comment by Grokafar** [comment]
I'm working on it :)

**Comment by andrew-bibb** [comment]
Getting there, I can now sit in front of a computer for 30 minutes or so before I have to knock off.  Problem was in the .pro file used to generate the translations.  Fixed there and renamed the incorrect ones so we should be good to go.

Grokafar: Great, looking forward to the translations.  I'm afraid however you may be losing ground as I'm pretty sure I've added the VPN and Tethering controls since you started.  As part of this fix I also regenerated all the .ts files.  VPN and Tethering had been on GitHub, but this last update addresses a really stupid thing I needed to do, support the known mispelling of `prefered`.  In the TranslateStrings class you'll now see entries for `prefered` and `preferred`. 

Thanks again for tackling this.
