### ISSUE TITLE
Add command line flag to disable "minimze" option.

### ISSUE THREAD

**Issue by klausenbusk** [andrew-bibb/cmst#147]
Hello

We use cmst as part of a digital signage solution, and it work pretty well.

We use jwm as window manager, but we have a little problem.

In the .jwmrc config, we have specified the `nofocus` for CMST which does `Prevents windows in this group from grabbing the focus when mapped.`. Which work most of the time, we then use F10 to bring CMST in front with `wmctrl -a "Connman System Tray"`.

Sometimes cmst pop out in front of Firefox, when for example the screen is rotated.

So my idea was to change F10 to execture `cmst -d` and set `layer:above` for CMST in .jwmrc, it works pretty well. There is only one problem, people can minimize CMST, and then access to CMST is gone. That can of course be fixed by using something like `wmctrl -a "Connman System Tray" || cmst -d`, but I will prefer if people couldn't minimize CMST and then was forced to close it.

So could you add a command line switch to start CMST with the minimize button removed?

Regards
Kristian

PS: Keep up the good work :)

**Comment by andrew-bibb** [comment]
I should be able to do that. May take a week or two.

Thanks for the suggestion.

**Comment by andrew-bibb** [comment]
Well we had a line of thunderstorms come through this evening so I was stuck indoors.  Got to work on this issue and I've updated the code here with my first attempt at this one.

New command line option is -M or --disable-minimize.  That is a capital M on the short form.

Can you take a look and let me know if this is what you want or if we are on the right path.

Thanks
A-

**Comment by klausenbusk** [comment]
Sorry I haven't got time to test this yet! Hopefully I will soon :)

Thanks for the great work!

**Comment by klausenbusk** [comment]
Hello @andrew-bibb 

Finally got time to test it, and it seems to work as expected.

I noticed if you start CMST without any options, it don't show minimize/maximize in the topbar, not sure if that the expected behavior? I use Gnome Shell 3.20 on ArchLinux if that have anything to say.

Regards Kristian

**Comment by andrew-bibb** [comment]
Kristian,

Glad the command line switch is working.

To the second question, it is expected behavior, but indirectly.  The main CMST window is a non-modal dialog.  In QT the QDialog class tells the window manager that the window should be decorated as a dialog which typically means no minimize or maximize buttons in the title bar.  I run the i3 tiling window manager so no applications on my desktop show those decorations.  I personally never noticed them as missing.

If you think the buttons would be important I could look at using a more general base class.  The QDialog gave me a couple of small things right out of the box, the resize grip at the bottom right is one I remember.  I don't think any of the features it provided would be all that hard to code, but all other things being equal "automatic" beats "not hard to do" every time.  If you think the buttons should be there for non-tiling WM's let me know and I'll look at changing the base class.

A-

**Comment by klausenbusk** [comment]
> If you think the buttons should be there for non-tiling WM's let me know and I'll look at changing the base class.

I think they should be there, but it isn't something I gonna use. So it you call.

Should I close this issue now? or wait for release or?

**Comment by andrew-bibb** [comment]
I'll close this one out.  I've got a couple of items ready to go, this being one, so I'm thinking about a release sometime mid-August, maybe a bit earlier.  There is still the better part of three cords of firewood in my driveway I've got to move and stack, so the mid-August date is probably safer.  

I'll probably create a new issue for the buttons.  I've found the issue tracker is a real easy way to keep an up to date to-do list for each of my various projects.  It will have a low immediate priority though, and definitely won't be started until the weather turns cold again.
