### ISSUE TITLE
Rescan button in the wireless tab

### ISSUE THREAD

**Issue by Alamot** [andrew-bibb/cmst#151]
I believe that adding a rescan button in the wireless tab would be very useful.
For example, if someone is moving around the wifi antenna etc. to get a better signal, he has to go to the status tab to press rescan and then return back again in the wireless tab to see the results and so on.

**Comment by andrew-bibb** [comment]
Thank you for the suggestion.  At first I wasn't sure it would work that way, but I've checked the documentation and it will. That's why I never answer issues until I've had my full day's allotment of caffine.  It makes a lot of sense to have a rescan button on the Wifi tab.

I'm actually about three weeks past when I wanted to do another release, so I'll add this one in and it should be in the next release.  I'm hoping for sometime this month - heavily weather dependent (as in it needs to rain - when it is nice I'm outside)
