### ISSUE TITLE
only activate vpn handling if  /usr/sbin/connman-vpnd is there

### ISSUE THREAD

**Issue by agaida** [andrew-bibb/cmst#155]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=842444

In short - please only activate the vpn-tab and try to the vpn daemon if the daemon is really installed, otherwise deactivate this tasks.

Thanks Alf

EDIT: (and maybe active)

**Comment by andrew-bibb** [comment]
In the latest version and release there is a command line option -n ( --disable-vpn) which will get you started up without the error message.  This can also be set as a preference in the Preferences tab so you don't need to do it every time.  Only mentioning that because it may take me a couple of days (week?) to get a check implemented so I can turn these off.  

Maybe it will easier than I anticipate, however I need to be out of town (out of the country actually) for some of next week, and getting ready for that trip is filling up my time at the moment.

**Comment by agaida** [comment]
ok, it's not that urgent and i have one big problem - i should not provide it with vpn off - that would result in bugs about vpn not working :D

**Comment by andrew-bibb** [comment]
I'm trying to squeeze a bit of time to work on this, interesting problem here is that if I disable the connman-vpn service then CMST segfaults on startup while something (probably systemd) automatically restarts the connman-vpn daemon.  Getting further and further into the weeds.

Understand not wanting to ship with vpn off, but the users experiencing the error could set it on their own machines to bypass the error until I figure out how to catch this automatically. It is only a message telling you that CMST could not connect to the connman-vpn daemon.  Probably should downgrade it from critical to warning.  

A-

**Comment by agaida** [comment]
ok, it's a question of philosophy - if vpn fails and there is no segfault - i see that vpn is greyed out and can read in the log why - so there is no need for a message. And if cmst segfault at startup because of the not activated service no message window appear ... :P

**Comment by andrew-bibb** [comment]
Segfaut is fixed - gads took me forever.  It was buried.

I've now got it so that if the connman-vpn daemon is not there then the VPN tab and the VPN  popup menu in the tray icon are both greyed out.  The popup message at startup is still there currently.  I'm going to reopen this as I tend to agree with your comments above.  Was originally written as an error, but compiling  ConnMan without VPN support is allowed, so therefore not really an error if we can't connect to the daemon.

**Comment by andrew-bibb** [comment]
Just did the PR to close this.  

THanks
