### ISSUE TITLE
Add org.cmst.roothelper.conf for Gentoo

### ISSUE THREAD

**Issue by evadim** [andrew-bibb/cmst#163]
This one with "netdev" group. After I edit system confiig manually VPN Editor works fine.

**Comment by evadim** [comment]
Corresponding bug at Gentoo bugzilla https://bugs.gentoo.org/show_bug.cgi?id=596744
But, seems no group exist and at Gentoo side it should be created during installation.

**Comment by andrew-bibb** [comment]
Looks like I need to put in the plugdev group for the Gentoo build.  Need to read the rest of the bug report, but what I've looked at so far seems pretty routine. I'll probably have this up in a day or two.

Thank you for the notification, this is exactly what I'm looking for with other distro's.

A-

**Comment by evadim** [comment]
I realize now what not  plugdev nor netdev present in fresh system. Connman/ofono packages doesn't create them either... plugdev more common.
In my system  netdev created by avahi. On system from guy in bug, plugdev created by Network Manager, seems because it used by modemmanager for manage usb devices.
I have TUN  device owned by root:

`crw-rw-rw- 1 root root 10, 200 мар  4 11:55 /dev/net/tun`

I'll test both of them with my openvpn server if actual connection works.

**Comment by andrew-bibb** [comment]
The group in the service file just needs to be some group defined in the distro.  Ideally it is defined for group members who can change basic network parameters, but could just as easily be the 'users' group.  

I just started looking at users and groups in Gentoo and at first pass it seems that groups need to be defined at the program install stage.  I'll really need to research this further to make sure I set up the file correctly.  It is not too hard, more making sure I do it right

**Comment by andrew-bibb** [comment]
I did a bit of looking and on Gentoo in order to use wpa-supplicant one must be in the wheel group.  I just uploaded a conf file with that setting.

To build with it run:
`qmake DISTRO=gentoo`
`make`
`make install` (as root)

Not sure on Ofono, but ConnMan should not need to create any groups to run. The only group CMST needs is something to allow the root helper to start.  Wheel actually seems like a very appropriate group for this.  

I'm going to keep this open as I'm not 100% sure it is correct.  If you could let me know one way or the other that would be great.

Thanks
A-

**Comment by andrew-bibb** [comment]
Seems like we have a solution to this one so I'm going to close it.  If I'm wrong please do not hesitate to reopen it.
