### ISSUE TITLE
VPN appears to attempt connection BEFORE wifi connection is established

### ISSUE THREAD

**Issue by mshelby** [andrew-bibb/cmst#164]
As title indicates, I have configured both a wifi connection and a VPN connection and set preferences to "retry failed connections" and "enable autostart."

When CMST automatically starts up the wifi will connect flawlessly, but the VPN connection event appears to be also attempting to start at the same time. The VPN always times out and fails to connect because it has not established a working wireless connection yet.

Is there a line that can be inserted using the provisioning editor telling the VPN connection to wait -n seconds before attempting to connect to VPN?

**Comment by andrew-bibb** [comment]
Neither of the boxes you have checked will do what you are intending.  The "retry failed connections" will only do anything if ConnMan reports that the topmost entry in the services list is in a "failed" state.  Then it will only retry establishing the connection if the topmost entry is a wifi technology.  That was really a hack I put in as some people were reporting difficulty getting a connection at startup.  I think it had to do with trying to get a connection before the network was up (just a guess).

The second (enable autostart) will only autostart CMST at boot.  It has nothing to do with starting or configuring ConnMan.

The suggestion to add something to the provisioning code won't work as the provisioning only assists with creating and editing the ConnMan config files.  There are no entries for delay start in the ConnMan config files.

Now that all that is out of the way.  VPN was an odd duck. There is a whole API devoted to it, but the ConnMan guys also allow limited access via the Services API.  I picked the Services API as I already had that in place by the time I got around to the VPN stuff.  The Services API is a bit limited for VPN, which is why the Configuration button in the Details tab grays out and becomes inactive when you select a VPN service.  You can look but you can't change.  There may be something in the real VPN API I can use.

Barring that I may be able to add a control to try and autostart a VPN connection, similar to what I did with the "retry failed connections" control.  It will be something CMST specific (nothing to do with ConnMan), but there are a few of those things floating around already.

By the way, I'm really glad someone finds the VPN connection stuff useful.  I think you are the first person I've heard from that is using it (I've heard from several that wanted me to turn it off) - so thanks.  And thank you for asking the question, I appreciate it.

A-

**Comment by andrew-bibb** [comment]
I didn't think Autostart would work with VPN services, but recent posts on the Connman developer mailing lists showed me that I was in error.  I've been trying it and I'm duplicating your error, and with ethernet, just not wifi.

I had started to code off a way of doing autostart without using the autostart property, but I've put that aside and am now trying to figure out why the proper way of doing it is not working.  Looks like a Connman bug, but I want to make sure there is no hidden setting somewhere before I report it.

**Comment by mshelby** [comment]
I have enjoyed reading of your thought  processes  and am confident you
will solve the issue!

**Comment by andrew-bibb** [comment]
2 years later, I believe this has been corrected at the ConnMan level in version 1.38.  I've been testing with wifi and VPN autoconnect (which went through major upgrades in the 1.38 release) and it is working at this end
