### ISSUE TITLE
Sizes of Technologies and Services subwindows(?) are not retained

### ISSUE THREAD

**Issue by Coacher** [andrew-bibb/cmst#173]
Hello.

I have Retain state option enabled in cmst. If I resize Technologies and Services subwindows(?) in Status tab their new sizes are not retained after restart.

**Comment by andrew-bibb** [comment]
I think you are right, when I put that control in I was more interested in overall geometry.  I should be able to put this in without too much trouble.  Just adding a couple of extra QSettings to save and read, probably about 4-6 lines of code.

Also wanted to let you know that I am getting and reading the issues.  This year though lot of things have just fallen apart all at the same time and I'm spending 2 or 3 weekends every month (since November) driving back and forth across New England, then starting work bright and early Monday morning.  I will get to these, but probably not until my schedule opens up a bit.

**Comment by Coacher** [comment]
No worries. Thank you for your time working on cmst.

**Comment by andrew-bibb** [comment]
You should be good to go on this one.  Thank you for reporting it.

**Comment by Coacher** [comment]
Works fine now. Thank you!
