### ISSUE TITLE
No signal percentage

### ISSUE THREAD

**Issue by jamtur01** [andrew-bibb/cmst#193]
CMST is not reporting any signal percentages.

![screenshot_20180831_004929](https://user-images.githubusercontent.com/4365/44893344-9d6e1f80-acb8-11e8-99f4-aa20ba6625eb.png)

This is Ubuntu 18.04 / KDE Plasma 5.13 / cmst 2018.01.06-3 amd64

**Comment by andrew-bibb** [comment]
Sorry about the delay getting back to you.  2018 was a difficult year for a variety of reasons.

Anyway, I think this may be at the Connman end.  Reason I am saying that is CMST will query the Connman service and return a variant map containing entries for Favorite, Connected, Security and Signal Strength. We are obviously getting the map because the first three have good values.  

This data will also appear in the  Details tab when you select the wireless service in the combobox.  Is it zero there also?  I would expect it to be, but if it is some value other than zero while the signal strength bar is zero then without a doubt it is a CMST problem.

**Comment by jamtur01** [comment]
I'll need to spin up that vm and test again.

**Comment by andrew-bibb** [comment]
It seems to be working now.  Not clear to me if you were using iwd, but that was a known problem with it.
