### ISSUE TITLE
CMST, connman, openbox

### ISSUE THREAD

**Issue by alan12345678** [andrew-bibb/cmst#210]
Love your GUI, absolutely splendid. One small but annoying issue:

I use connman to control my wired connection. I don't have a wi-fi on this machine. Starts and connects fine, CMST works to the point I can set certain prefs, e.g. color of icon.

But for some unclear reason the entire right hand side of the GUI prefs is "greyed out" i.e inactive. I did go to my local .conf and set the flat for "start minimised", but I'm stuck with how to specify the preferred icon from manual input in the .conf

More importantly though - do you have any idea why I have this strange permissions problem? I am using systemd-resolved, if that makes any difference. That's enforcing TLS_over_DNS, but that's surely connman territory, nothing a GUI should need to touch?

edit: I'm guessing I might be missing a package somewhere. Didn't see anything on installation, but sometimes a dependency gets missed.

**Comment by alan12345678** [comment]
my apologies - I was being so unbelievably thick!!

Doh - it's that "use start options" flag!!

Oh dear.

**Comment by andrew-bibb** [comment]
Glad you got it sorted out.  The design is a bit odd.  This program started life with having only start options (command line options). I realized not long after that as the GUI grew command line options alone were not going to cut it.  I started putting in regular GUI options (left side) but there were a lot of people already using the command line options (right side) so we ended up with both types.  Probably not totally bad as I've written it so that any time you supply an option on the command line it will take precedence over the start option set in the GUI, so it gives one a way to test options without actually changing settings.

**Comment by alan12345678** [comment]
Thank you for that. I offer the further remarks simply because having read through the issues before posting, I can see that you care about your code and like  to give it thought.

Therefore:

mine was a relatively tiny issue - caused largely by a level of ignorance. That said, UI design is important. It ought to offer the user a simple and easily understood interface. This is to say that it's actually slightly confusing to use the word "start options" right there as the first flag, particularly when one is new to the interface.

Someone such as myself tends to take the word 'start' to mean "yes, I want this app to start" and thus treated it not only as the 'autostart' option (wrongly of course) but also never even noticed that checking or un-checking was the very thing which gave access to said further options - my attention being presently focused left-side.

I suggest this is simply a naming issue. If, for example, that very first switch were labelled something like "use extended configuration" or "use additional options", it would have been IMMEDIATELY clear both what this switch was doing, as well as letting me know it was NOT the one I was needing to 'autostart' the tray icon.

I entirely accept that it clearly says "autostart" as the last option lower left.

There's a similar small confusion present in the choice between "enable system tray popups" and using notification daemon. I know what the difference is supposed to be, I'm simply pointing out that purely in terms of the words used, the descriptions are a bit confusing.

All that said, it's a lovely little app. Works superbly well with Connman :)

**Comment by andrew-bibb** [comment]
Thanks for the feedback, I'm a structural engineer, not a UI designer, so feedback on the UI is welcome.  Just uploaded a few fixes to the UI that hopefully make the controls a bit clearer.

I also expanded the "whats this" text on the items to hopefully make it a bit more clear what each does. Not sure if you picked up on it or not but I'm using the "whats this" feature to provide much of the documentation for the program.  Most controls and labels have help text assigned to them for this purpose.

The last one (system tray popups and notification daemon) I left as is because they are two (admittedly similar but) different things.  If you have an idea as to how I could change them let me know.  Anything else feel free to open an issue.

Thanks
A-
