### ISSUE TITLE
Raw HTML code in KDE Plasma popup

### ISSUE THREAD

**Issue by toxpal** [andrew-bibb/cmst#216]
When "system tray popups" option is enabled, it displays raw HTML code instead of new lines. Here's how it looks like on latest KDE Plasma: https://i.postimg.cc/vTn6r82t/conn.png

**Comment by andrew-bibb** [comment]
Thank you for reporting this.  I'm not running KDE and I just checked it on my end and I'm not getting the HTML, however I also am not running on a WIFI connection so first place I'll look is the code to create the WIFI popup message, I suspect that is where the error is.  More than likely something at my end and not the KDE end. Hopefully a simple fix.

A-

**Comment by toxpal** [comment]
I also believe it will be an easy fix. Just checked all the notifications in my KDE desktop, and all apps display new lines in notifications properly, so probably just a small issue in cmst itself.

**Comment by progandy** [comment]
KDE has fixed their code to adhere to the StatusNotifierItem specification. That has broken HTML support in QSystemTrayIcon->tooltip. You could try to simply use newlines instead.

https://bugs.kde.org/show_bug.cgi?id=422616

**Comment by andrew-bibb** [comment]
Progandy,

Thank you for this.  My "this was going to be a simple fix" was turning into a "no matter what I try it works here and I can't find it" sort of problem.  I did find about 5 lines of superfluous code that I can remove so that was good. I had looked around a bit for KDE problems with tray popup's but was not finding much beyond 2014 or so.  This particular piece of code really just uses the <br> tag so replacing with newlines should be simple (hmm, where have I heard that before).
