### ISSUE TITLE
Tray icon stopped working in mate

### ISSUE THREAD

**Issue by corvus1** [andrew-bibb/cmst#237]
Tray icon recently stopped showing in mate, although the app itself seems to start and run just fin. Disabling the DE-specific switches seems to fix the situation. 

It is perhaps relevant that I recently upgraded to mate 1.26.

**Comment by andrew-bibb** [comment]
This is interesting.  I'm coming to the end of the outdoor season and gearing up for programming season and one of the things I was planning to do is disable those DE specific switches.  This is the first I've heard in about 4 or 5 years that somebody needed them.   They were put in very early in the program when something (I think maybe at the QT end) changed and are a complete hack.  We never did find out what was causing the issue but the fixes could seem to work around it.  Obviously now I'll be leaving them in and maybe try to find the root cause of the problem so we don't need a hack "fix".

**Comment by corvus1** [comment]
I somewhat narrowed this down, back a couple of months ago, when I was investigating for #240 
So what really changed is Qt5PatchCollection (https://community.kde.org/Qt5PatchCollection) got applied in Gentoo.

However, more importantly, I think you somewhat misread my report. _Disabling_ the DE-specific code fixes the icon, not enabling it. So if the plan is to remove that DE-specific hack anyway, maybe it's not even worth investigating any further.

**Comment by andrew-bibb** [comment]
I probably did misread it.  Came in at a somewhat bad time for me and I was fairly distracted.  Around these parts we get about 3 months of nice weather with maybe another month at each end where it is acceptable.  I try not to spend a lot of time inside on my computer those few months.  Today however we are back to normal; sun, clouds, rain, snow, sun, sleet, then sun again but pretty darn cold.  Expect to see me here a lot more for the next couple of months.  

I've been toying with removing the hack code for some time.  I've not heard of anybody actually using it for the past 3 or 4 years at least.  I think before I make a decision I'll try those DE's out in a virtual machine to see if it is still needed.

**Comment by corvus1** [comment]
yeah, as far as the weather goes, it's very much the same way here

**Comment by andrew-bibb** [comment]
Just uploaded the 2021.12.19-1 which removes all the MATE and XFCE custom code.
