### ISSUE TITLE
RIP Project owner

### ISSUE THREAD

**Issue by yarons** [andrew-bibb/cmst#307]
This project is officially disowned, sadly Andrew Bibb passed away last year, may his soul rest in peace:
https://www.burlingtonfreepress.com/obituaries/pbur0673903

Feel free to fork this project and modify whatever you desire.

**Comment by trevorbibb** [comment]
Hi @yarons, thanks for submitting. 

I am Andrew's son and am planning on keeping this project going if it makes sense to do so by reviewing/approving/merging PRs and as they come in. I do not have my father's background in C and have no immediate plans to learn so if someone more familiar wants to fork to add new features or otherwise maintain, feel free to do so but in absence of that, I don't intend to let this go dormant if people are still making contributions.

**Comment by yarons** [comment]
My deep condolences for your loss!

Good luck and feel free to close this issue if you think it's irrelevant.
Thank you for the good spirit and may his memory live on.
