### ISSUE TITLE
i haven't tray icon on archlinux with xfce

### ISSUE THREAD

**Issue by Dea1993** [andrew-bibb/cmst#34]
i've installed connman and cmst from AUR, but i haven't tray icon on xfce, why?? when i launch cmst i don't receive error on terminal

CMST version
CMST - Connman System Tray 14.10.15-1
thanks

**Comment by andrew-bibb** [comment]
I'm going to close this one out now for a couple of reasons.  One is I've done as much as I can do with it.  The work around for both XFCE and MATE works on my test systems.

Primary reason though is that I have been playing with the new Blueplate system tray client by Trilby and it seems not to work in either XFCE or MATE.  Blueplate is a pure C application with no dependencies on external toolkits (QT or GTK).  Since this plain, vanilla, C tray client will not work in either of these systems I'm assuming it is a problem with the tray server and not the client programs.  In other words an upstream problem which needs to be fixed there.  I will however leave the work arounds in the CMST code base for people that need them.

**Comment by wido-gg** [comment]
Hello,

I've recently found CMST and I really like it. But I'm hitting this error and is driving me nuts.

I have debian Stretch fully up-to-date (at this time is November 2015). I'm running Enlightenment E19 and use stalonetray as a systray. The version I have for cmst is 2015.09.10.

I've read that this kind of c-pure trays does not work with cmst? is there any other kind of workaround? I do have some qt and kde libs, including breeze and oxygen themes, as I use lots of K apps, but it seems not to use that theme

**Comment by andrew-bibb** [comment]
Could you do me a favor and open up a new issue on this.  I only saw it because I happen to get emails even on closed issues.

I'll look at standalone tray, but one thing I did very recently was fix an issue where the tray icon would not show up in Plasma5.  Code in GitHub is current, but I've not done a release with it yet.
