### ISSUE TITLE
Notification Daemon changes the look of my popups...

### ISSUE THREAD

**Issue by ghost** [andrew-bibb/cmst#44]
Hi Andrew,

Now this is a wierd one I just don't understand, so let me say it like this. 

I use OpenVPN from the command line, but it runs in a GUI created by Yad, which is a fork of Zenity; 

http://sourceforge.net/projects/yad-dialog/

In the Yad script that creates the gui, I have it call two notification scripts to tell me when the connection is up or down, which gives me a notification popup. These popups since I use  xfce4-notifyd are themed.

I've been using OpenVPN this way for 2-3 years, and I've never seen a glitch with the notification popups until now with cmst.

I've tested this several times, and when I have the Notification Daemon checked in cmst and I run OpenVPN, the popup notifications change color.

Here's a screen shot showing how the color for one theme I created looks;

http://i.imgur.com/XfD6YyC.jpg

Here's how it ends up looking when I use the Notification Daemon with cmst and I start OpenVPN;

http://i.imgur.com/UgBM29B.jpg

Like I said this is a weird one and I don't know how, but it's happening...

**Comment by andrew-bibb** [comment]
There is nothing in the desktop notification specification about themes (I just read the entire thing again).  Appearance of the popups is entirely up to the notification daemon based on information sent by the client.  If theme elements are changing it is the daemon not handling the received information in a consistent way, and if I had to make a guess it is because of the theme responding differently to different senders.

I'm closing this because as I see it there is nothing I can do from the CMST end.
