### ISSUE TITLE
Sytem Tray Icons Have Black Box Without Compositor...

### ISSUE THREAD

**Issue by ghost** [andrew-bibb/cmst#47]
In Openbox I use tint2-svn version, and I use Compton X Compositor, but I noticed if I don't run Compton the system tray icon will appear with a blackbox around it, it's not appearing transparent.

http://i.imgur.com/LShsz6X.jpg

All the other apps I run that have a system tray icon will appear normal, but I have noticed that sometimes when there are some apps sitting in the system tray and I turn Compton on and off, other icons too will appear this way. But it always happens to cmst tray icons, meaning any iconset I use on my box, they all appear this way...

**Comment by andrew-bibb** [comment]
Check out also issue #81 which is kind of the continuation of this thread now that we're on QT5.4.  I just uploaded a version that implements a fake transparency for the icons.  I know it is a bit hackish, but it does seem to work.

**Comment by moulei** [comment]
Hey Andrew,

Hope you had a good Holiday(s)...

So some people are getting black or white boxes?

I compiled 5.4 and I still get the black box...

Oh no Hackish from the Master? LOL... ;)

**Comment by andrew-bibb** [comment]
Very nice Christmas, and thank you for asking.  Had all of the kids and their husbands, wives, girl friends (and dogs) over all at the same time - which happens very rarely these days. Hope yours was good as well.   

Curious on the box color, most everybody (me included) now has the white box instead of the black box, although I do believe the problems were fixed on some systems.  In the threads I linked to over on #81 some people think it may have to do with the graphics card being used, and now that I've typed that sentence it occurs to me that I may be able to check that.   One more thing to the list.  I'm actually hoping that since DropBox spent the summer rewriting their code to use the QT libraries that they'll not want to go back, and that they will have enough clout to get this problem fixed.

Anyway the best I can do for now is the fake transparency which does seem to work.

**Comment by moulei** [comment]
Yes nice holidays, but not white and chilly like you... :)

Ahhh well I'm using Nvidia GPU with nvidia-driver-340.58

Yep just checked it again turning compton off I get a black box, never seen white...

Hmm

Ok fake transparency here I come... :)
