### ISSUE TITLE
RX/TX Filling Up /var/log/messages

### ISSUE THREAD

**Issue by ghost** [andrew-bibb/cmst#7]
Hi Andrew,

Not sure if this is a connman issue or from cmst but I noticed all the RX/TX activity is flooding /var/log/messages. Everything that is constantly being done is going to messages. I need to change this behaviour so the log isn't being flooded...

```
May 23 16:59:51 slack connmand[1872]: eth0 {RX} 29408 packets 25673224 bytes
May 23 16:59:51 slack connmand[1872]: eth0 {TX} 28251 packets 8751848 bytes
May 23 16:59:51 slack connmand[1872]: eth0 {newlink} index 2 address 10:BF:48:2F:F3:D3 mtu 1500
May 23 16:59:51 slack connmand[1872]: eth0 {newlink} index 2 operstate 6 <UP>
May 23 16:59:51 slack connmand[1872]: wlan0 {newlink} index 3 address 00:08:CA:F7:DF:BA mtu 1500
May 23 16:59:51 slack connmand[1872]: wlan0 {newlink} index 3 operstate 2 <DOWN>
May 23 17:00:01 slack connmand[1872]: lo {newlink} index 1 operstate 0 <UNKNOWN>
May 23 17:00:01 slack connmand[1872]: eth0 {RX} 29408 packets 25673224 bytes
May 23 17:00:01 slack connmand[1872]: eth0 {TX} 28251 packets 8751848 bytes
May 23 17:00:01 slack connmand[1872]: eth0 {newlink} index 2 address 10:BF:48:2F:F3:D3 mtu 1500
May 23 17:00:01 slack connmand[1872]: eth0 {newlink} index 2 operstate 6 <UP>
May 23 17:00:01 slack connmand[1872]: wlan0 {newlink} index 3 address 00:08:CA:F7:DF:BA mtu 1500
May 23 17:00:01 slack connmand[1872]: wlan0 {newlink} index 3 operstate 2 <DOWN>
May 23 17:00:11 slack connmand[1872]: lo {newlink} index 1 operstate 0 <UNKNOWN>
May 23 17:00:11 slack connmand[1872]: eth0 {RX} 29408 packets 25673224 bytes
May 23 17:00:11 slack connmand[1872]: eth0 {TX} 28251 packets 8751848 bytes
May 23 17:00:11 slack connmand[1872]: eth0 {newlink} index 2 address 10:BF:48:2F:F3:D3 mtu 1500
May 23 17:00:11 slack connmand[1872]: eth0 {newlink} index 2 operstate 6 <UP>
May 23 17:00:11 slack connmand[1872]: wlan0 {newlink} index 3 address 00:08:CA:F7:DF:BA mtu 1500
May 23 17:00:11 slack connmand[1872]: wlan0 {newlink} index 3 operstate 2 <DOWN>
May 23 17:00:21 slack connmand[1872]: lo {newlink} index 1 operstate 0 <UNKNOWN>
May 23 17:00:21 slack connmand[1872]: eth0 {RX} 29408 packets 25673224 bytes
May 23 17:00:21 slack connmand[1872]: eth0 {TX} 28251 packets 8751848 bytes
May 23 17:00:21 slack connmand[1872]: eth0 {newlink} index 2 address 10:BF:48:2F:F3:D3 mtu 1500
May 23 17:00:21 slack connmand[1872]: eth0 {newlink} index 2 operstate 6 <UP>
May 23 17:00:21 slack connmand[1872]: wlan0 {newlink} index 3 address 00:08:CA:F7:DF:BA mtu 1500
May 23 17:00:21 slack connmand[1872]: wlan0 {newlink} index 3 operstate 2 <DOWN>
May 23 17:00:31 slack connmand[1872]: lo {newlink} index 1 operstate 0 <UNKNOWN>
```

**Comment by andrew-bibb** [comment]
I know, but I've had almost no time to work on this.  Seems like lately I've been spending all my time working on or working around things which are really upstream issues: in addition to this one, the XFCE tray icon not showing, MATE tray icon not showing (not the same fix as XFCE), the fake transparency for the tray icon, OpenBox and Tint2 tray issues.....

Anyway when I asked the developers about your other issue I told them I was working on this (figured there would be a better chance of getting a response) so better get back to it.  There is only one of me and I seem to be losing ground.

**Comment by andrew-bibb** [comment]
I was not aware that wicd was dead.  Never used it myself, but I see comments about it all over the place, maybe not recently though now that you mention it.  

Last 3 things I've worked on with this program are hacks to work around bugs (QT I think) and they are all adding weight to the program - and I think it is starting to bug me (pun not intended, but appropriate).  Each one has taken a significant amount of time to work out.   

Counters are definitely a PC based option, and Connman itself is mainly geared and developed towards handheld devices.   I suspect if the counters are ever going to move off the experimental state, so that the system logs are no longer flooded, it will need somebody like me to do it.  I've got another guy asking about doing a translation, so I'm probably going to declare a string freeze very soon.  The practical result of that will be a week or two or three where I can't work on the UI, or at least not in the main branch.  Give me time to get caught up on other things.

**Comment by moulei** [comment]
Yep wicd has gone to the dust bin unfortunately.

This is also why I say ditch the what's this and tooltips to make the GUI less weighted and bloated, as you seem not want to be involved with adding more weight.

YES there's a BIG HOLE open right now for a nice light weight alternative, I can really see this taking off you IF you KEEP that GOAL in mind.

Let's look at it this way, most Geeks out there don't like the NetworkManager, so if you can really get this moving and keep it light and working nice, I think this can really make a run for it in distros! :)

**Comment by moulei** [comment]
Wicd isn't in development, NetworkManager is a pig, so what does it leave us?

---> cmst :)

Just realize and remember this, and the fact that connman is walking on a differnent path that opens up networking in other ways, this really seems like the future next!

**Comment by moulei** [comment]
Ahh sorry hit the close button by mistake and then had to make this new post to open it again...

**Comment by moulei** [comment]
Wooo wicd just release a new version in over 2 years 8 months, holy crap, I thought it was dead;

https://launchpad.net/wicd/+download

Well I just tried again to get a hold of the dev for connman on that bug report, if he doesn't answer this time, I'm going to have to go back playing with wicd until this gets worked out...

**Comment by andrew-bibb** [comment]
I had not really thought too much about weight, I was more griping about the amount of time I've been spending working around upstream problems, and the fact that there are now several code blocks of pretty hack stuff in the main program.  Truth be told it is probably more the later than the former.  

Anyway your messages made me look and I've pretty much decided that a QT based program that minimizes to the system tray is not really light, or at least it is not light in my book.  Actually there is very little reason to have the whole thing minimized in the system tray.  CMST is handy for communicating with Connman to change something - but how often does one really need to do that.  I'm looking around to see if there are any other options for the systemtray and I may have found one.  It is brand new, written in C (ugh - I really don't know C), but when running HTOP reports 0% CPU and 0.1% memory usage on my machine (the developer says he gets 0 and 0 on his machine).  If I can get it to work it will have very little functionallity as far as user interaction, but it sure will be light.  I'd like to be able to at least click the icon to open the full CMST GUI, but at the moment it won't  process mouse clicks.  We'll see if I can change that.

**Comment by moulei** [comment]
Hi Andrew,

Sorry for your troubles, yeah coding must be a bitch at times LOL...

Just enjoy it for what it is, cause you've done a great job, hell of a lot more that I could ever do, I just don't have the patience for it... Not even sure my brain could ever getting into coding LOL...

Well wicd is python that uses gtk...

What about gtk or wxWidgets too for a gui?

**Comment by mrunion** [comment]
I'm just piping in with the same "stop CMST and the journal stops filling up". Every 10 seconds it dumps a set of counter data it seems. I am posting here so I can keep up with any news.

FWIW I also run Arch Linux.

Thanks for all you are doing!

**Comment by andrew-bibb** [comment]
I just finished up (as in 30 minutes ago) the Connman module for Trilby's Blueplate system tray client program, mentioned 3 posts up.  As an aside, I have managed to modify it so that a mouse click on the icon will open CMST.  This is super light weight, running between 0 to 0.1% CPU and memory load on my system.  Much lower than having CMST itself running in the system tray when it really is not needed. 

To your question though, since that is done I've now got a green field open to work on this issue. No guarantee however that the Connman guys will accept my patch if I can even do it.  I am going to give it a shot.

**Comment by andrew-bibb** [comment]
For anybody following: I've not given up, but last weekend I put over 6 hours into finding this and all I've accomplished is that I know there it is not.  It will probably prove to be immediately obvious and trivial once I find it, but so far it is slow going.

**Comment by diefans** [comment]
I was just trying out your UI and ran into the same issue.

I was able to minimize the log spam by setting the ``Counter Update Rate=599`` (higher values weren't not possible??? ). So these logs are somehow triggered by your counter settings with a default 10 second interval.

**Comment by andrew-bibb** [comment]
Frequency of the logs is triggered by the counter settings, but the actual log entry is from Connman.  I posted the question to the Connman developers and they said counters are experimental and have debug code in them.  They suggested I could submit a patch to get rid of the debug code, but darned if I can find where it all is.  It is not in the counters.c file, guess that would have been too easy.    

Right now the only way to completely eliminate the log entries is to start CMST with the disable counters command line switch (or from the settings in the preferences tab).  I poke at the Connman code every now and again looking for this, but my real hope is the developers fix it.  To date no joy on that end.  

I'm not on my Linux machine at the moment, and I'm going to be gone for the remainder of the weekend.  When I get back I'll look at the rate setting, but at the moment I don't recall setting an upper limit.  Are you trying from the command line or from the preferences tab?  If preferences it may be a default  value in the widget that I never corrected.  Anyway I'll take a peek when I get back and if it is wrong I'll get it fixed.

**Comment by progandy** [comment]
I'm not sure this will ever get fixed. There were already two patch series in 2011 addressing this problem. Thr first one added an option to suppress connman_info messages. It got rejected because it masked the problem instead of solving it. https://lists.connman.net/pipermail/connman/2011-November/006981.html

The second patchset replace connman_info with connmand_debug, but there was no reaction
https://lists.connman.net/pipermail/connman/2011-November/006992.html

**Comment by andrew-bibb** [comment]
difans: There is a maximum on the UI control of 600.  I put it there but it was just becasue I needed some number.  I'll change it to something much larger.

progandy:  The second link basically points to something I was hoping the problem was, specifically the DBG macro, but (unless I very mistaken) it is only for running Connman in debug mode.  Actually what I was referring to when I said "too easy" in the post above.   Your first link however is very interesting.  There are a few things in there I had not stumbled across yet, and even if that patch was not accepted this is the first hard lead I've had in where to look.  

Weather is finally getting nicer here so I'm spending more time in my gardens and less on the computer.  This issue is still alive though and thanks both for commenting.

**Comment by gladstonedigital** [comment]
I just ran into this problem today on Debian 9 stable. Any progress?

**Comment by andrew-bibb** [comment]
No, I'm afraid not.  Counters are still considered experimental by the ConnMan people.  In retrospect I should have never implemented a tab that used them.  What you need to do is start cmst with the -c switch, or under preferences put a check in the disable counters box in Start Options.

**Comment by gladstonedigital** [comment]
Any chance you could flip the behavior so counters are off by default and you pass a flag to turn them on? It's pretty strange to have to set a flag to keep the program from cluttering the log, normally it works the other way around :P

**Comment by andrew-bibb** [comment]
You know, that is a very good idea.  It will definitely be in the next release.  I'll have to put a prominent notice on the page here, but I do think it is very much worth it.

**Comment by andrew-bibb** [comment]
I just uploaded code that changes the behavior of the counters from enabled by default to disabled by default.  If you used the Preferences box to control enable or disable counters then the program will pickup on that and make the change for you automatically.  If someone uses the command line switch then they'll need to change that.  Still things to do for documentation on this, but it does seem to be working.  I'm going to close this one out.
