### ISSUE TITLE
Tray icon has white background instead of transparent

### ISSUE THREAD

**Issue by lockheed** [andrew-bibb/cmst#81]
Since last two AUR cmst updates, the tray icon became white instead of transparent.

My setup of Arch Linux is: Openbox + Stalonetray + compton

**Comment by andrew-bibb** [comment]
Thanks for coming over.  

The links below may be of interest, both have to do with Dropbox and a white background system tray icon suddenly appearing.  From what I can tell Dropbox changed to using QT for the GUI late this year.     

https://bbs.archlinux.org/viewtopic.php?id=190940
https://bbs.archlinux.org/viewtopic.php?id=190992

My immediate reaction is probably the same problem, but I'll see if there is anything I can tweak to correct it.  We had hopes that QT5.4 would fix the problems we had previously, but as I mentioned in the AUR thread it seems like we now have a white background instead of black, when it is supposed to be transparent.

**Comment by andrew-bibb** [comment]
I just built the new QT based DropBox and ran it and sure enough the tray icon shows up with a white background in my i3bar.  This is not looking good as far as me being able to do anything with it, but I'll keep plugging away looking and trying different things.

**Comment by andrew-bibb** [comment]
I've just uploaded a version that implements a fake transparency for the tray icons.  It is a little hackish, and definitely needs to be cleaned up from my end (way too may image conversions, at least I think there are), but it does work.  To use it call cmst with the new commandline option 
--fake-transparency [color].

color is a hex RGB value.  For instance on my i3 bar I call it with **--fake-transparency 222222** as my tray background is color 0x222222.

If somebody could try this out and let me know if it is an adequate work around I'd appreciate it.

**Comment by andrew-bibb** [comment]
I wanted to move the discussion from the closed thread to here.  The closed one I consider to be for Qt5.3 (therefore dead) and this one QT5.4.  

Up/Down controls have been removed in the latest code uploaded to GitHub (an easy one - yeah!)

Best I think I can do with the transparent icon on the transparent panel is to have you pick a color on your background for the fake transparency.

**Comment by moulei** [comment]
Well for colors, then it would be for a wallpaper, since the tint2 panel is transparent, and that would make me work, LOL, since I change my look all the time... :)

Hey no worries, if it works for others in the meantime, GREAT! :)

I personally don't disable compton, I only reported this when I saw it happening with it disabled for those that might disable their composite manager...

**Comment by andrew-bibb** [comment]
I forgot to mention (carry over from the closed thread), I did try CMST with QT5.4 on 3 different computers.  This is on a bootable USB that I can plug into other machines.  One has an NVIDIA graphics card, another integrated Intel, and the third I'm not sure on but probably integrated intel.  On all 3 in my i3-wm the icon background was white, so I'm thinking this is less an issue with the graphics card and more an issue between QT and the various system trays.

**Comment by moulei** [comment]
Sorry point me plz to the closed thread?

Ok on QT...

**Comment by andrew-bibb** [comment]
My last post in thread 47, middle of the last paragraph.

**Comment by moulei** [comment]
ok, I posted there a few days ago...

**Comment by superbly** [comment]
I encountered the same problem with Arch Linux 4.0.2.-1, i3wm 4.10.2-1, Dropbox 3.4.6
Dropbox updates itself and overwrites the current icons.
As my system try is black I created a black icon set.  
https://github.com/superbly/dropbox_black_icons

**Comment by andrew-bibb** [comment]
Not sure if your question relates to CMST or not.  If it does the fake transparency should work for the CMST tray icons.  I'm using i3 as well and it makes the icon unobtrusive (when I use it that is, mostly I've gone over to the Blueplate tray client as described in the wiki).

**Comment by andrew-bibb** [comment]
Well now, for the first time in months I started Dropbox and discovered their icon background is no longer white.  Tried CMST by removing the fake transparancy and it also now shows properly.  Looks like this one finally got squashed upstream so I'm closing the issue.

**Comment by andrew-bibb** [comment]
Well now, for the first time in months I started Dropbox and discovered their icon background is no longer white.  Tried CMST by removing the fake transparancy and it also now shows properly.  Looks like this one finally got squashed upstream so I'm closing the issue.

**Comment by andrew-bibb** [comment]
Well now, for the first time in months I started Dropbox and discovered their icon background is no longer white.  Tried CMST by removing the fake transparancy and it also now shows properly.  Looks like this one finally got squashed upstream so I'm closing the issue.
