### ISSUE TITLE
Wireless Tab - PSK,wps - Also Signal Strenght Moves GUI...

### ISSUE THREAD

**Issue by moulei** [andrew-bibb/cmst#83]
Hi Andrew,

Under the wireless tab when the SSID are listed, I see PSK, I'm assuming for pre shared key, and wps, all I know is for wifi protected setup...

Also when looking over other network managers in the past I've only seen them list these Protocols; WEP, WPA, WPA2

Why aren't you using just wep, wpa, and wpa2?

Also I noticed as the signal strength changes it moves the gui, not the entire gui, just the window where it says; Name Favorite... This section and where the ssid are located it will move...

**Comment by andrew-bibb** [comment]
Well this is annoying, I ansered this over my lunch hour and my answer seems to have disappeared.  Here goes again...

I'm reporting the security settings as Connman reports them.  From the API:

> array{string} Security [readonly]
			If the service type is WiFi, then this property is
			present and contains the list of security methods
			or key management settings.

> Possible values are "none", "wep", "psk", "ieee8021x" and also "wps".

> This property might be only present for WiFi services.

I'll take a look at the shifting text.  Probably a text padding thing again.

**Comment by moulei** [comment]
Hmm I don't even know what wps stands for other than wifi protected setup you find on routers...

I don't know if it's just me or what, but I think seeing psk and wps stupid, after all there is only typically used wep, wpa, wpa2 and pre shared keys can be used anywhere... but only seeing psk, you don't know whether you are dealing with wpa or wpa2.

In Networking I always thought when looking at something like this, we were more concerned with knowing Protcols not Modes... Hmm

wep does appear in cmst so that leaves psk for either wpa, or wpa2...

Last time I checked in the NetworkManger, there was only a lock showing and if you moused over, you just read, either; wep, wpa, wpa2, also wicd only shows wep, wpa, wpa2...

I personally would really love to see this changed, as to what seems to still be normal, and I've never seen any network device display psk, wsp till now in all my geek years, LOL...

HEY it's not a reflection on you, it's just this connman is really starting to get on my nerves...

**Comment by moulei** [comment]
Here's another odd thing I just found out, wicd doesn't use/need wpa_supplicant, so why does connman always seem to start it at bootup?

The way I've always seen wpa_supplicant is if you wanted to manually control, granted I guess we are dealing with two things here I keep forgetting, seperate from one another; connman & cmst.

So shouldn't using cmst, not create the need for having wpa_supplicant started at boot time?

**Comment by andrew-bibb** [comment]
Not sure on Slackware, but in Arch wpa_supplicant is a hard dependency for Wicd. It is an optional dependency for Connman.

Your diagram above is not quite correct.  Connman works via plugins.  If you want wifi support you need  wpa_supplicant,  for Bluetooth support you need bluez, Ofono for whatever it is that provides, etc. If you don't have a particular plugin then Connman will not manage that type of connection.

Connman deals with all these plugins, ranks all the possible connections based on criteria including what you have done in the past, and then makes every effort to get a connection into the "online" state with minimal or no user intervention.

All CMST does is provide a GUI interface between Connman, which communicates to the world via DBus, and the user.  Up until the introduction of the provisioning editor it was nothing more or less.  With the provisioning editor we do go off the reservation slightly, and actually that was quite a lot further than I had ever anticipated taking the program.  If you are into metaphors, CMST is the flea at the very far end of the tail of the dog. Remove CMST and your connections will still be managed by Connman - it will not know the difference,

For the text; as mentioned above we're a GUI front end for Connman so we're just reporting what that program feeds us.  With the translations now implemented it is a trivial matter for anyone to change the text to their liking.  Fire up qt-linguist and find the text you want to change (it is in trstring.cpp) and enter the text you want to see in the translation box.   Select "release" from the qt-linguist file menu and then rebuild.  The file cmst_en_US is mainly used for managing plural forms, but if you look closely at it you'll see there are case changes also, for instance "p2p" is translated as "P2P". You can translate the security settings to "Mickey", "Minnie", "Goofy", and "Donald", the program won't care. In fact when I was working getting the translation structure implemented I changed the checkbox on the first page from "All Devices Off" to "Turn those damn radios off - and get off my lawn".  I thought it was amusing....

**Comment by moulei** [comment]
I read online that wicd doesn't use wpa_supplicant, it makes it's own, so maybe it's wrapped into Arch, to be sure it's there in case it's going to be needed, you know like tacking on another depenedancy, sorta thing...

Ok I have wpa_supplicant and when connman runs I see in the log /var/log/supplicant it say it was initialized, so it's working...

The Flea LMAO! :) Well don't let the Dog Bite or Bark! 

qt-linguist, hmm I don't have this, so you saying the PSK,wsp you could change that output if you wanted to?

Thing is, I wouldn't know how, because PSK can be on any Protocol is my understanding, WPA or WPA2... And WEP is already being shown in cmst, so that leaves it out, and as far as wps, I still don't know what the heck that is being reported? Hmm

Ahhh so maybe if you have time you can make cmst report the protocols like any other network manager would? As WEP, WPA, WPA2 That would be really appreciated, maybe it can be like, now that I think about it, a 'Pluggin' for people who want to change this?

Lawn! LOL...

**Comment by moulei** [comment]
Hi Andrew,

I made a report thinking by what you said, that cmst is just reporting the PSK.wps like connman, but according to the developer connman reports the SSID and encryption;

https://01.org/jira/browse/CM-671

I guess by what he's saying connman is going to show it the way I'm think it should but it's not....

**Comment by andrew-bibb** [comment]
Here is a link to the document, if you can find wpa2 in it your eyes are better than mine.

http://git.kernel.org/cgit/network/connman/connman.git/tree/doc/service-api.txt

Also this from the file config-format.txt
> - Security: The security type of the network. Possible values are 'psk'
  (WPA/WPA2 PSK), 'ieee8021x' (WPA EAP), 'none' and 'wep'. When not set, the
  default value is 'ieee8021x' if an EAP type is configured, 'psk' if a
  passphrase is present and 'none' otherwise.

I also did a grep in the connman source code for wpa2 (and WPA2) and the only instances are examples in the agent-api document, the change log, and the above quote out of config-format.txt.

**Comment by moulei** [comment]
That's really odd that there's no listing for WPA/WPA2

I understand connman can be running in any type of environment, small or large, but when using on just a laptop, or just a home user, it would certainly be nice to elminate all the other stuff going on and only present to the end-user the basic protocols, wep, wpa, wpa2...

I'm starting to get the feeling looking over connman that the end-user is being left out here...

**Comment by andrew-bibb** [comment]
Well, it's not like they are hiding it.  From the Connman web page:
>Who It’s For
ConnMan is utilized primarily by operating system vendors, system builders (including system Integrators and Original Device Manufacturers) who are building customized Linux solutions.

I originally started using it because it knocked about 10 seconds off the boot time of my desktop machine, and started CMST because at the time there were not a whole lot of ways to conveniently set up connections.

**Comment by moulei** [comment]
You know, I can't remember if I read that and forgot it...

Oh well SUCKS to be me, just can't get a damm break here, LOL...

Well maybe something can be done in the future to change it so it just lists the basic protocols...

Hmm guess wicd is going to be the best light weight end-user alternative then...

**Comment by moulei** [comment]
The developer tells me wiith your UI you can make connman show the protocls how you like, as WEP, WPA, WPA2...

Hmm

**Comment by andrew-bibb** [comment]
I'll see what he means.  I suspect I'll need to take several pieces of information which together will tell what type it is.

**Comment by andrew-bibb** [comment]
Actually no.  After I typed my message above I went over and read the latest response from Patrick, and he is telling you the exact same thing I am.  Only possible difference is the psk->WPA/WPA2, although it was alluded to in some of the links I gave you (duplicated by Patrick).  It is not possible to differentiate between WPA and WPA2 using Connman alone.  See also this reply from the Connman mailing lists (February 2012):


> How can I distinguish between WPA-PSK and WPA2-PSK correctly with ConnMan?

>ConnMan doesn't export that distinction through D-Bus. This is intentional as
we didn't see the benefit of telling a user that his AP does wpa2 or wpa. It's
more confusing than anything else, and from a user point of view, the only
thing you need to care about is the passphrase.  

If you wish to see WPA/WPA2 instead of "psk" in the wifi tab that is where you need to edit your personal copy of the cmst_en_US.ts file.  My intention is to have the base CMST report what Connman reports, since if you are used to using the command line interface that is what you are used to seeing.  You mentioned above that you didn't have Linguist on your system, but previously in a different thread you mentioned that you clicked on a .ui file and opened up Designer, so my bet is that you also may have Linguist.  Typically they are packaged together.

**Comment by moulei** [comment]
Ok my mistake on what Pat said...

Well I have things I need to do now for some other changes in life, so I've gone back to wicd for now.

Sorry don't have time once again to play with cmst, and this time it might be for good, might even be ditching computing all together, been at it a very very very long time, and now, it's time for some changes in life...

So I must say Ado again Andrew, and thanks for all you've done. Keep up the great work though! :)

Cheers

**Comment by andrew-bibb** [comment]
Well good luck.  You know where we are.

Actually not a lot planned new for here until some of the Connman features move from experimental to stable, I'm mainly thinking of the new Peer API.  Also need to finally jump over to the counters problem and try to get that patch done.

While working on the lightweight Blueplate system tray icon module for Connman I've disovered I like playing around in C and at the very low level necessary to do that.  I'll probably be spending more time with things like that as well.

**Comment by moulei** [comment]
Cheers... :)
