### ISSUE TITLE
Close button should minimize to system tray

### ISSUE THREAD

**Issue by hagabaka** [andrew-bibb/cmst#85]
In CMST, clicking the [X] button in the window title bar will exit the program. However most programs that display system tray icons will continue running when you close their main windows, or they might have an option to behave this way. I think CMST should follow this convention.

Also, I suggest changing the "Minimize" button to say "OK", and moving the "Exit" button to the left so that users won't habitually click it, as it's now similarly located as an "Apply" or "OK" button.

**Comment by andrew-bibb** [comment]
I think you are right on the behavior for window bars.  I use i3 so I don't have any window bars, hence I tend not to think about them.

The minimize button is mainly for users of i3 and such who have no other way to minimize.  Exit button I agree with - don't know how many times I've hit it by mistake.  Thought it was just me being clumsy, but if other people are hitting it it means that button needs to find a better home.

**Comment by andrew-bibb** [comment]
I just uploaded code to change the behavior of clicking the [X] button in a window bar to minimize (if the system tray icon is visible) instead of close.  Also moved the Exit button away from the Minimize button.  Not sure I'm happy with it in the new place, but also not sure where else we could relocate it to. Any ideas let me know.

Can you check this out and let me know if it does what you want.

I need to thank you for posting the issue.  I had all of the infrastructure to do this in place, but had never connected the last piece of it.  As near as I can tell I must have forgotten about it, in fact about a week ago I removed the closeEvent handler wondering why I'd ever put it there in the first place since it was not doing anything.  Anyway, now I know and it is back, and all the parts are connected.

**Comment by hagabaka** [comment]
That's perfect for me. Thanks a lot!
Closed by b74c07f16b9f801e75c14c6c76ce9d2136cd1631
