### ISSUE TITLE
Icon names in . desktop files

### ISSUE THREAD

**Issue by nbvcxz** [andrew-bibb/cmst#92]
I noticed that you use absolute path for icons in cmst.desktop and cmst-autostart.desktop . As cmst icons are placed in hicolor which is in fact the base for all other icon themes - **it would be better to use just the icon names and let a theme to choose** (with auto fallback to hicolor if none in the icon theme).

**Comment by andrew-bibb** [comment]
Icons in the devel branch have had the paths removed.  I suspect I'm going to move them into the master branch for the next release since they don't violate the string freeze, and there a few other changes insdie them as well.

There is a discussion in the pull requests, still on going even though I did the PR and it is now closed about the desktop files (issue 89).  I think I'm going to revamp both even further.
