### ISSUE TITLE
Discussion: use QWebView for authentication page?

### ISSUE THREAD

**Issue by hagabaka** [andrew-bibb/cmst#94]
Currently when connman detects that a wifi network requires browser authentication, the Agent Input dialog lets the user select or enter a browser, and opens the authentication page with the browser. Then the user needs to click the OK button to let connman know that the authentication is finished, so that connman can change the connection state from "Ready" to "Online".

Perhaps we can open the authentication page directly within a QWebView. This would likely be faster than launching an external browser, since many browsers have to load history and cache and notify a running instance etc.

As a step further, we might be able to use signals such as onLoadFinished and onUrlChanged to detect when the user has completed authentication, and reply to connman. This way the user would no longer need to click a 'Launch Browser" button and an "OK" button.

This would add QtWebKit as a dependency, but we could compile the feature optionally.

What do you think?

**Comment by andrew-bibb** [comment]
I very much would like to have program self contained.  No matter how many browsers we list there will always be someone else who wants a different one.  I was glad when you put in the XDG fallback to help with that issue.

On the other hand though, QWebView is a huge dependency.  I've been playing with it on some of my other projects.  

I think if we could make it optional as you suggest the scales tip in favor of doing it.  I did a release last week so the string freeze has been removed and the "devel" branch where your code was has been merged into "master".  If you want to try it I'd say go for it.  Just pull "master" and since we're not in a string freeze let "devel" sit on the side.
