### ISSUE TITLE
Settings not saved

### ISSUE THREAD

**Issue by kminh** [andrew-bibb/cmst#95]
Hi there, thank you for this useful package.

One thing I have notice (using https://aur.archlinux.org/packages/cmst/) is I can't save any setting. For example I select "Use System Icon Theme" but next time CMST starts that setting is unchecked.

Also does CMST supports Cinnamon's system tray icon? Basically I would like to use the same icon that Network Manager would use.

Thank you, please keep up the good work.

**Comment by andrew-bibb** [comment]
I've been away for a week and just got back (not ignoring your issue).

To save Settings you need to have the top-left most checkbox in the Preferences tab (first checkbox in the Interface group) checked.  The checkbox title is "Retain Settings".  This will create a settings file in ~/.config/cmst, which is just a plain text file in .ini format.  

That entire dialog tab has grown quite a bit since I first created it and I'm afraid some of the logic has broken down with all the additions.  Maybe what I need to do is grey out the other widgets unless that one is checked.  

I have no clue on Cinnamon, I've not tried it and have no feedback from others one way or the other.  Cinnamon is a fork or branch (or some other variation) of Gnome and there have been some problems with the QT tray icon working with XFCE and MATE, which are both some variation or at least based on GTK.  If it does not show up you might try with one of the special command line options for XFCE or Mate, also available from the Preferences tab.  If nothing works can you open a new issue and I'll try to install Cinnamon on a VM and see if I can find some hack to make it work.  The special command line options for XFCE and MATE are really hacks until the QT guys can figure out a fix.  It is by the way related to the issue of DropBox tray icons not showing up in either of those DE's, and I understand that there is a concerted effort to solve it officially.   

I'm glad you like the program, and thank you for the positive feed back.

**Comment by kminh** [comment]
Thanks you Andrew for you reply.

In fact the system tray icon is showing up nicely with Cinnamon, I was just wondering if there's a way to change the icon so that it uses Gnome theme (also Cinnamon)'s standard tray icon for network (same one Network Manager is using).

Something like this: https://csl.cs.wisc.edu/sites/default/files/1x_images/Gnome3-1.png (just the icon of course).

**Comment by andrew-bibb** [comment]
The icons both in the system tray and in the interface should change once the --icon-theme setting takes.  From your initial question I'm pretty sure the setting never took as this setting (and all the others) are read and set when CMST starts up.

The current version here at GitHub has a new feature implemented where you can specify the icon theme to use.  If no theme is specified then it falls back to the system theme, and if no icon is found for that it falls back to the hard coded icons.  Not officially released yet so not in the AUR, but it does work if you want to download and manually build.  It requires the latest version of QT as the ability to do this was only added in the most recent QT update.  

If the --icon-theme option is set and if the icons are found then these are the Freedesktop.org icon names used:

wired: "network-transmit-receive"
wifi: "network-transmit-receive"

If you want the tray icon to show different signal strengths then you need to use the built in ones as the Freedesktop specification does not have wifi icons for different signal strengths.

This whole system theme stuff was a feature request.  At the time I picked system icons that seemed appropriate based only on their names, and I said if someone wants different ones let me know.  Nobody ever said anything, but the offer still holds.  If there is a Freedesktop.org named icon you would rather see let me know and I'll put it in.  For instance as soon as I get done typing this I'm going to change the two above to:

wired: network-wired
wifi: network-wireless

**Comment by kminh** [comment]
That sounds great, I will wait for the official version then :).

Btw, this is what I could find in the default Gnome theme:
```
network-wired-acquiring-symbolic.svg
network-wired-disconnected-symbolic.svg
network-wired-no-route-symbolic.svg
network-wired-offline-symbolic.svg
network-wireless-acquiring-symbolic.svg
network-wireless-connected-symbolic.svg
network-wireless-encrypted-symbolic.svg
network-wireless-hotspot-symbolic.svg
network-wireless-no-route-symbolic.svg
network-wireless-offline-symbolic.svg
network-wireless-signal-excellent-symbolic.svg
network-wireless-signal-good-symbolic.svg
network-wireless-signal-none-symbolic.svg
network-wireless-signal-ok-symbolic.svg
network-wireless-signal-weak-symbolic.svg
```

Does that mean we can support signal strengths for `--icon-theme` as well?

**Comment by andrew-bibb** [comment]
Those are only for the Gnome theme (and maybe a few themes as well).  The only way I can even attempt to make this portable is to adhere to the freedesktop.org naming specification.    The "standard" freedesktop.org icon names are listed at this link:

http://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html

**Comment by hagabaka** [comment]
On my system the gnome and Adwaita themes have `network-wireless-signal-{none,weak,ok,good,excellent}`, and the Oxygen theme has `network-wireless-connected-{00,25,50,75,100}`. The Breeze theme doesn't have any related icons except `network-wireless`.

QIcon supports fallbacks so it's possible to use these icons only when they exist in the theme, but I don't know if it would be worth the effort.

**Comment by andrew-bibb** [comment]
The effort involved is certainly an issue, but I think there will always be some theme that someone wants that has it's own naming scheme. There is of course no guarantee that any theme will implement all of the standard icons (not required by the standard), but at least the names are known in advance.  

We already do the fallback to the hard coded icons.  I think to do this we would need an icon name sieve, unless of course QT will allow multiple fallbacks, but I've not ever seen that it has that ability.

**Comment by kminh** [comment]
IMO we simply have an option to use the theme's symbolic icon, if not available (blank icon or an error of some sort) the user can choose to use the built-in one, no need for complicated fallback mechanism.

Anyway should I make a separate issue for this request?

**Comment by andrew-bibb** [comment]
Basically that is the way it works now, only restriction is that the symbolic icon name must be one of the names defined by the freedesktop.org icon naming specification.  

If you'd like to remove that restriction then certainly open up a new issue (there is no way to split apart existing issues).  If your first question was answered then you can also close this one out.

I've got an idea as to how I might be able to implement non-standard icon names, and allow the user to specify these.  It will probably involve a new class, but I've been thinking of doing something similar for my media player so if I do implement it the code would be used for both projects. Lot will depend on if I can keep it from becomming a huge mess of code - whenever you need to interact with people code expands very fast.
